testcases:
  ternary_if:
    name: "Ternary operators vs if statements"
    languages:
      - js
      - rb
    question: What will the value of result be
    correct_answer: 10
    samples:
      - ternary
      - if_statement
  reduce_for:
    name: "Reduce function vs for loops"
    languages:
